import React, { useState } from "react";
import { Volume2, PlayCircle, ShieldAlert, BookOpen, Smile, Info, Download, RefreshCw, Filter } from "lucide-react";

export default function DetailModal({ view, mistakes, suggestions, scores, onPlayWord, onAnalyzeAnother }) {
  // Severity filter state for Mistakes page: 'all' | 'high' | 'medium' | 'low'
  const [severityFilter, setSeverityFilter] = useState("all");

  const getSeverity = (score) => {
    if (score < 45) return { text: "High", color: "bg-red-50 text-red-750 dark:bg-red-950/20 dark:text-red-400 border-red-200 dark:border-red-900/60" };
    if (score < 60) return { text: "Medium", color: "bg-amber-50 text-amber-750 dark:bg-amber-950/20 dark:text-amber-400 border-amber-250 dark:border-amber-900/60" };
    return { text: "Low", color: "bg-slate-50 text-slate-700 dark:bg-slate-800/40 dark:text-slate-400 border-slate-200 dark:border-slate-800" };
  };

  const handleNativePlayClick = (word) => {
    alert(`[Model Playback] Playing native pronunciation reference for "${word}". (Feature Placeholder)`);
  };

  const handleDownloadReport = () => {
    if (!scores) return;
    
    const { pronunciation_score, accuracy_score, fluency_score, completeness_score, summary } = scores;
    
    const reportText = `PRONUNCEAI ASSESSMENT REPORT
==================================
Overall Pronunciation Score: ${pronunciation_score}/100
Clarity (Accuracy): ${accuracy_score}%
Fluency Score: ${fluency_score}%
Confidence (Completeness): ${completeness_score}%

AI Evaluation Summary:
${summary || "N/A"}

Pronunciation Mistakes Detected (${mistakes.length}):
${mistakes.map((m, idx) => `${idx + 1}. "${m.clean_word}" - Score: ${m.score}% - IPA Target: ${m.ipa}\n   Coach Tip: ${m.tip}`).join("\n\n")}

Practice Focus Areas:
1. Target phoneme drills on: ${mistakes.slice(0, 3).map(w => `"${w.clean_word}"`).join(", ") || "General Vowels"}
2. Voicing contrasts between voiced and unvoiced consonants.
3. Natural pausing rate at punctuation marks (Aim for 120-140 WPM).

Generated by PronounceAI.
Practice English pronunciation with AI-powered speech analysis.
`;

    const blob = new Blob([reportText], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `pronounce_ai_report_${Date.now()}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  // Filter mistakes list
  const filteredMistakes = mistakes.filter((m) => {
    const sev = getSeverity(m.score).text.toLowerCase();
    if (severityFilter === "all") return true;
    return sev === severityFilter;
  });

  if (view === "mistakes") {
    return (
      <div className="w-full space-y-4 text-left transition-colors duration-200">
        
        {/* Table Toolbar / Filter */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-slate-100 dark:border-slate-700/60 pb-3">
          <h3 className="text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400">
            Pronunciation Mistakes Table
          </h3>
          
          <div className="flex items-center space-x-2 text-[10px] font-bold">
            <span className="text-slate-400 dark:text-slate-500 flex items-center">
              <Filter className="h-3 w-3 mr-1" />
              Filter:
            </span>
            <button
              onClick={() => setSeverityFilter("all")}
              className={`px-2 py-1 rounded border transition-colors ${
                severityFilter === "all"
                  ? "bg-[#458393] dark:bg-[#34A99D] text-white border-transparent"
                  : "bg-white dark:bg-slate-800 border-slate-200 dark:border-slate-800 text-slate-600 dark:text-slate-400 hover:bg-slate-50 dark:hover:bg-slate-750"
              }`}
            >
              All
            </button>
            <button
              onClick={() => setSeverityFilter("high")}
              className={`px-2 py-1 rounded border transition-colors ${
                severityFilter === "high"
                  ? "bg-[#458393] dark:bg-[#34A99D] text-white border-transparent"
                  : "bg-white dark:bg-slate-800 border-slate-200 dark:border-slate-800 text-slate-600 dark:text-slate-400 hover:bg-slate-50 dark:hover:bg-slate-750"
              }`}
            >
              High
            </button>
            <button
              onClick={() => setSeverityFilter("medium")}
              className={`px-2 py-1 rounded border transition-colors ${
                severityFilter === "medium"
                  ? "bg-[#458393] dark:bg-[#34A99D] text-white border-transparent"
                  : "bg-white dark:bg-slate-800 border-slate-200 dark:border-slate-800 text-slate-600 dark:text-slate-400 hover:bg-slate-50 dark:hover:bg-slate-750"
              }`}
            >
              Medium
            </button>
            <button
              onClick={() => setSeverityFilter("low")}
              className={`px-2 py-1 rounded border transition-colors ${
                severityFilter === "low"
                  ? "bg-[#458393] dark:bg-[#34A99D] text-white border-transparent"
                  : "bg-white dark:bg-slate-800 border-slate-200 dark:border-slate-800 text-slate-600 dark:text-slate-400 hover:bg-slate-50 dark:hover:bg-slate-750"
              }`}
            >
              Low
            </button>
          </div>
        </div>

        {/* Mistakes List / Table */}
        <div className="p-4 rounded-lg border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-800 shadow-sm">
          {filteredMistakes.length > 0 ? (
            <div className="overflow-x-auto">
              <table className="w-full text-xs text-slate-700 dark:text-slate-350 border-collapse">
                <thead>
                  <tr className="border-b border-slate-200 dark:border-slate-750 text-slate-500 dark:text-slate-450 font-medium bg-slate-50/50 dark:bg-slate-800/50">
                    <th className="py-2.5 px-3 text-left font-semibold">Word</th>
                    <th className="py-2.5 px-3 text-center font-semibold w-24">Severity</th>
                    <th className="py-2.5 px-3 text-left font-semibold">Expected (IPA)</th>
                    <th className="py-2.5 px-3 text-center font-semibold">Replay</th>
                    <th className="py-2.5 px-3 text-left font-semibold">Suggestion / Issue</th>
                  </tr>
                </thead>
                <tbody>
                  {filteredMistakes.map((item, idx) => {
                    const severity = getSeverity(item.score);
                    return (
                      <tr 
                        key={idx} 
                        className="border-b border-slate-100 dark:border-slate-750/50 hover:bg-slate-50/70 dark:hover:bg-slate-750/30 transition-colors"
                      >
                        <td className="py-2.5 px-3 font-semibold text-slate-900 dark:text-slate-100">
                          "{item.clean_word}"
                        </td>
                        <td className="py-2.5 px-3 text-center">
                          <span className={`px-2 py-0.5 rounded text-[10px] font-bold border ${severity.color}`}>
                            {severity.text}
                          </span>
                        </td>
                        <td className="py-2.5 px-3 font-mono text-[11px] text-[#458393] dark:text-[#34A99D] font-bold">
                          {item.ipa}
                        </td>
                        <td className="py-2.5 px-3 text-center">
                          <div className="flex justify-center space-x-1.5">
                            {item.start !== null && item.end !== null && (
                              <button
                                onClick={() => onPlayWord(item.start, item.end)}
                                className="p-1 rounded border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-850 hover:bg-slate-50 dark:hover:bg-slate-700/60 text-slate-650 dark:text-slate-350 transition-colors"
                                title="Play my segment"
                              >
                                <Volume2 className="h-3.5 w-3.5" />
                              </button>
                            )}
                            <button
                              onClick={() => handleNativePlayClick(item.clean_word)}
                              className="p-1 rounded border border-transparent bg-[#458393] dark:bg-[#34A99D] hover:bg-[#347483] dark:hover:bg-[#2c9186] text-white transition-colors"
                              title="Play native reference"
                            >
                              <PlayCircle className="h-3.5 w-3.5" />
                            </button>
                          </div>
                        </td>
                        <td className="py-2.5 px-3 text-[11px] text-slate-600 dark:text-slate-400 leading-relaxed">
                          {item.tip}
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          ) : (
            <div className="flex flex-col items-center justify-center py-8 text-slate-500">
              <Smile className="h-6 w-6 text-emerald-500 mb-2" />
              <p className="text-xs font-semibold text-slate-700 dark:text-slate-300">No mistakes found for this severity filter.</p>
              <p className="text-[10px] text-slate-400 dark:text-slate-500 mt-0.5">Toggle filters above to review issues.</p>
            </div>
          )}
        </div>
      </div>
    );
  }

  if (view === "suggestions") {
    const mispronounced = mistakes.map(m => m.clean_word);
    const hasErrors = mispronounced.length > 0;
    
    const targetSounds = hasErrors 
      ? `Practice phonetic word targets: ${mispronounced.slice(0, 3).map(w => `"${w}"`).join(", ")}.`
      : "Focus on maintaining speaking rate steadiness (120-140 WPM).";

    const practiceSentence = hasErrors
      ? `Drill sentence: "We must review detailed suggestions to increase clarity and reduce mistakes."`
      : 'Drill sentence: "English pronunciation requires consistent practice and detailed feedback."';

    return (
      <div className="w-full space-y-6 text-left transition-colors duration-200">
        
        {/* Header toolbar */}
        <div className="flex items-center justify-between border-b border-slate-100 dark:border-slate-700/60 pb-3">
          <h3 className="text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400">
            Practice Suggestions
          </h3>
          
          <div className="flex space-x-2">
            <button
              onClick={handleDownloadReport}
              className="flex items-center space-x-1 px-3 py-1.5 rounded-lg bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-800 text-[10px] font-bold text-slate-700 dark:text-slate-350 hover:bg-slate-50 dark:hover:bg-slate-700/60 transition-colors shadow-sm"
            >
              <Download className="h-3 w-3 text-[#458393] dark:text-[#34A99D]" />
              <span>Download Report</span>
            </button>
            <button
              onClick={onAnalyzeAnother}
              className="flex items-center space-x-1 px-3 py-1.5 rounded-lg bg-[#458393] dark:bg-[#34A99D] hover:bg-[#347483] dark:hover:bg-[#2c9186] text-[10px] font-bold text-white transition-colors shadow-sm"
            >
              <RefreshCw className="h-3 w-3" />
              <span>Analyze Another</span>
            </button>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          
          {/* Focus sounds */}
          <div className="p-4 rounded-lg border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-800 shadow-sm space-y-2">
            <div className="flex items-center space-x-1.5 text-xs font-bold text-slate-800 dark:text-slate-250 border-b border-slate-100 dark:border-slate-700/60 pb-1.5">
              <ShieldAlert className="h-4 w-4 text-[#458393] dark:text-[#34A99D]" />
              <span>Focus Sounds</span>
            </div>
            <p className="text-xs text-slate-600 dark:text-slate-400 leading-relaxed">
              {targetSounds}
            </p>
            <p className="text-[10px] text-slate-400 dark:text-slate-550">
              Pay close attention to syllable weight and vowel reductions in long syllables.
            </p>
          </div>

          {/* Exercises */}
          <div className="p-4 rounded-lg border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-800 shadow-sm space-y-2">
            <div className="flex items-center space-x-1.5 text-xs font-bold text-slate-800 dark:text-slate-250 border-b border-slate-100 dark:border-slate-700/60 pb-1.5">
              <BookOpen className="h-4 w-4 text-[#458393] dark:text-[#34A99D]" />
              <span>Exercises</span>
            </div>
            <p className="text-xs text-slate-750 dark:text-slate-300 italic bg-slate-50 dark:bg-slate-900/40 p-2.5 rounded border border-slate-150 dark:border-slate-800">
              {practiceSentence}
            </p>
            <p className="text-[10px] text-slate-400 dark:text-slate-550">
              Record yourself reading this sentence multiple times, comparing speaking speed and transitions.
            </p>
          </div>

          {/* Daily Practice speaking tips */}
          <div className="p-4 rounded-lg border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-800 shadow-sm space-y-2">
            <div className="flex items-center space-x-1.5 text-xs font-bold text-slate-800 dark:text-slate-250 border-b border-slate-100 dark:border-slate-700/60 pb-1.5">
              <Smile className="h-4 w-4 text-[#458393] dark:text-[#34A99D]" />
              <span>Daily Practice & Tips</span>
            </div>
            <ul className="text-xs text-slate-600 dark:text-slate-400 space-y-1.5 list-disc pl-4 leading-relaxed font-medium">
              <li>Record yourself speaking 1 paragraph daily to build rhythm memory.</li>
              <li>Practice consonant release: ensure ending sounds (/d/, /t/, /g/, /k/) are crisply finished.</li>
              <li>Exaggerate your lip movements when drilling new vowel layouts.</li>
            </ul>
          </div>

          {/* AI Recommendations */}
          <div className="p-4 rounded-lg border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-800 shadow-sm space-y-2">
            <div className="flex items-center space-x-1.5 text-xs font-bold text-slate-800 dark:text-slate-250 border-b border-slate-100 dark:border-slate-700/60 pb-1.5">
              <Info className="h-4 w-4 text-[#458393] dark:text-[#34A99D]" />
              <span>AI Recommendations</span>
            </div>
            <div className="space-y-2 text-xs text-slate-600 dark:text-slate-400 leading-relaxed font-normal">
              <div>
                <span className="font-semibold text-slate-700 dark:text-slate-350">Voiced/Unvoiced contrasts:</span> Practice the transition between 's' and 'z'. Voicing vibratory cords turns /s/ into /z/.
              </div>
              <div>
                <span className="font-semibold text-slate-700 dark:text-slate-350">Diphthong glides:</span> When reading diphthong vowels like /eɪ/ (as in "progress" or "application"), ensure your tongue glides smoothly from one sound to another.
              </div>
            </div>
          </div>

        </div>
      </div>
    );
  }

  return null;
}
